FROM alpine:3.15
RUN apk add --no-cache postgresql14
ENV PGDATA=/var/lib/postgresql/data
RUN set -x \
 && su postgres -c initdb \
 && install -o postgres -g postgres -m 700 -d /run/postgresql \
 && printf %s\\n \
  "listen_addresses='0.0.0.0'" \
  "wal_level=logical" \
  "log_timezone=UTC" \
  "timezone=UTC" \
  > $PGDATA/postgresql.conf \
 && printf %s\\n \
  #      db  user       addr method
  "host  all pwduser    all password" \
  "host  all md5user    all md5" \
  "host  all sha256user all scram-sha-256" \
  "host  all all        all trust" \
  "local all all            trust" \
  > $PGDATA/pg_hba.conf \
 && su postgres -c "pg_ctl --wait start" \
 && psql -U postgres -v ON_ERROR_STOP=1 \
  -c " create role pwduser login password 'secret' " \
  -c " set password_encryption = 'md5' " \
  -c " create role md5user login password 'secret' " \
  -c " set password_encryption = 'scram-sha-256' " \
  -c " create role sha256user login password 'secret' "

USER postgres
CMD ["postgres"]
