FROM node:10.16.0-alpine
# FROM node:12.9-alpine
# FROM node:14.11.0-alpine3.12
RUN apk add --no-cache \
  --repositories-file /dev/null \
  --repository https://mirror.ps.kz/alpine/v3.10/main \
  postgresql-client
CMD node --no-warnings test/test.js
